//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionCaja.ServiceReferenceSM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSM.ISesionManager")]
    public interface ISesionManager {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uSesionManagerIntf-ISesionManager) del mensaje obtenerIDSesionProductoRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#obtenerIDSesionProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse obtenerIDSesionProducto(OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#obtenerIDSesionProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse> obtenerIDSesionProductoAsync(OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uSesionManagerIntf-ISesionManager) del mensaje obtenerIDSesionCotizacionRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#obtenerIDSesionCotizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse obtenerIDSesionCotizacion(OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#obtenerIDSesionCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse> obtenerIDSesionCotizacionAsync(OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uSesionManagerIntf-ISesionManager) del mensaje cerrarSesionProductoRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#cerrarSesionProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse cerrarSesionProducto(OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#cerrarSesionProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse> cerrarSesionProductoAsync(OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uSesionManagerIntf-ISesionManager) del mensaje cerrarSesionCotizacionRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#cerrarSesionCotizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse cerrarSesionCotizacion(OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uSesionManagerIntf-ISesionManager#cerrarSesionCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse> cerrarSesionCotizacionAsync(OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIDSesionProducto", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class obtenerIDSesionProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idEquipo;
        
        public obtenerIDSesionProductoRequest() {
        }
        
        public obtenerIDSesionProductoRequest(string idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIDSesionProductoResponse", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class obtenerIDSesionProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public obtenerIDSesionProductoResponse() {
        }
        
        public obtenerIDSesionProductoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIDSesionCotizacion", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class obtenerIDSesionCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idEquipo;
        
        public obtenerIDSesionCotizacionRequest() {
        }
        
        public obtenerIDSesionCotizacionRequest(string idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIDSesionCotizacionResponse", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class obtenerIDSesionCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public obtenerIDSesionCotizacionResponse() {
        }
        
        public obtenerIDSesionCotizacionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesionProducto", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class cerrarSesionProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public cerrarSesionProductoRequest() {
        }
        
        public cerrarSesionProductoRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesionProductoResponse", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class cerrarSesionProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public cerrarSesionProductoResponse() {
        }
        
        public cerrarSesionProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesionCotizacion", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class cerrarSesionCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public cerrarSesionCotizacionRequest() {
        }
        
        public cerrarSesionCotizacionRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesionCotizacionResponse", WrapperNamespace="urn:uSesionManagerIntf-ISesionManager", IsWrapped=true)]
    public partial class cerrarSesionCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public cerrarSesionCotizacionResponse() {
        }
        
        public cerrarSesionCotizacionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISesionManagerChannel : OperacionCaja.ServiceReferenceSM.ISesionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SesionManagerClient : System.ServiceModel.ClientBase<OperacionCaja.ServiceReferenceSM.ISesionManager>, OperacionCaja.ServiceReferenceSM.ISesionManager {
        
        public SesionManagerClient() {
        }
        
        public SesionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SesionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SesionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SesionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse OperacionCaja.ServiceReferenceSM.ISesionManager.obtenerIDSesionProducto(OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest request) {
            return base.Channel.obtenerIDSesionProducto(request);
        }
        
        public string obtenerIDSesionProducto(string idEquipo) {
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest inValue = new OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest();
            inValue.idEquipo = idEquipo;
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse retVal = ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).obtenerIDSesionProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse> OperacionCaja.ServiceReferenceSM.ISesionManager.obtenerIDSesionProductoAsync(OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest request) {
            return base.Channel.obtenerIDSesionProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoResponse> obtenerIDSesionProductoAsync(string idEquipo) {
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest inValue = new OperacionCaja.ServiceReferenceSM.obtenerIDSesionProductoRequest();
            inValue.idEquipo = idEquipo;
            return ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).obtenerIDSesionProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse OperacionCaja.ServiceReferenceSM.ISesionManager.obtenerIDSesionCotizacion(OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest request) {
            return base.Channel.obtenerIDSesionCotizacion(request);
        }
        
        public string obtenerIDSesionCotizacion(string idEquipo) {
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest inValue = new OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest();
            inValue.idEquipo = idEquipo;
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse retVal = ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).obtenerIDSesionCotizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse> OperacionCaja.ServiceReferenceSM.ISesionManager.obtenerIDSesionCotizacionAsync(OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest request) {
            return base.Channel.obtenerIDSesionCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionResponse> obtenerIDSesionCotizacionAsync(string idEquipo) {
            OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest inValue = new OperacionCaja.ServiceReferenceSM.obtenerIDSesionCotizacionRequest();
            inValue.idEquipo = idEquipo;
            return ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).obtenerIDSesionCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse OperacionCaja.ServiceReferenceSM.ISesionManager.cerrarSesionProducto(OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest request) {
            return base.Channel.cerrarSesionProducto(request);
        }
        
        public bool cerrarSesionProducto(string idSesion) {
            OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest inValue = new OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest();
            inValue.idSesion = idSesion;
            OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse retVal = ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).cerrarSesionProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse> OperacionCaja.ServiceReferenceSM.ISesionManager.cerrarSesionProductoAsync(OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest request) {
            return base.Channel.cerrarSesionProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionProductoResponse> cerrarSesionProductoAsync(string idSesion) {
            OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest inValue = new OperacionCaja.ServiceReferenceSM.cerrarSesionProductoRequest();
            inValue.idSesion = idSesion;
            return ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).cerrarSesionProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse OperacionCaja.ServiceReferenceSM.ISesionManager.cerrarSesionCotizacion(OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest request) {
            return base.Channel.cerrarSesionCotizacion(request);
        }
        
        public bool cerrarSesionCotizacion(string idSesion) {
            OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest inValue = new OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest();
            inValue.idSesion = idSesion;
            OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse retVal = ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).cerrarSesionCotizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse> OperacionCaja.ServiceReferenceSM.ISesionManager.cerrarSesionCotizacionAsync(OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest request) {
            return base.Channel.cerrarSesionCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionResponse> cerrarSesionCotizacionAsync(string idSesion) {
            OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest inValue = new OperacionCaja.ServiceReferenceSM.cerrarSesionCotizacionRequest();
            inValue.idSesion = idSesion;
            return ((OperacionCaja.ServiceReferenceSM.ISesionManager)(this)).cerrarSesionCotizacionAsync(inValue);
        }
    }
}
