//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionCaja.ServiceReferenceCotizacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCotizacion.ICotizacion")]
    public interface ICotizacion {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uCotizacionIntf-ICotizacion) del mensaje obtenerCotizacionRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uCotizacionIntf-ICotizacion#obtenerCotizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse obtenerCotizacion(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uCotizacionIntf-ICotizacion#obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse> obtenerCotizacionAsync(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uCotizacionIntf-ICotizacion) del mensaje obtenerCotizacionesRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uCotizacionIntf-ICotizacion#obtenerCotizaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse obtenerCotizaciones(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uCotizacionIntf-ICotizacion#obtenerCotizaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse> obtenerCotizacionesAsync(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:uCotizacionIntf")]
    public partial class TWSCotizacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string descripcionField;
        
        private double compraField;
        
        private double ventaField;
        
        /// <comentarios/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        public double Compra {
            get {
                return this.compraField;
            }
            set {
                this.compraField = value;
                this.RaisePropertyChanged("Compra");
            }
        }
        
        /// <comentarios/>
        public double Venta {
            get {
                return this.ventaField;
            }
            set {
                this.ventaField = value;
                this.RaisePropertyChanged("Venta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCotizacion", WrapperNamespace="urn:uCotizacionIntf-ICotizacion", IsWrapped=true)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int codigo;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(string idSesion, int codigo) {
            this.idSesion = idSesion;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCotizacionResponse", WrapperNamespace="urn:uCotizacionIntf-ICotizacion", IsWrapped=true)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion @return;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCotizaciones", WrapperNamespace="urn:uCotizacionIntf-ICotizacion", IsWrapped=true)]
    public partial class obtenerCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public obtenerCotizacionesRequest() {
        }
        
        public obtenerCotizacionesRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCotizacionesResponse", WrapperNamespace="urn:uCotizacionIntf-ICotizacion", IsWrapped=true)]
    public partial class obtenerCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion[] @return;
        
        public obtenerCotizacionesResponse() {
        }
        
        public obtenerCotizacionesResponse(OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICotizacionChannel : OperacionCaja.ServiceReferenceCotizacion.ICotizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CotizacionClient : System.ServiceModel.ClientBase<OperacionCaja.ServiceReferenceCotizacion.ICotizacion>, OperacionCaja.ServiceReferenceCotizacion.ICotizacion {
        
        public CotizacionClient() {
        }
        
        public CotizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CotizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse OperacionCaja.ServiceReferenceCotizacion.ICotizacion.obtenerCotizacion(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion obtenerCotizacion(string idSesion, int codigo) {
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest inValue = new OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse retVal = ((OperacionCaja.ServiceReferenceCotizacion.ICotizacion)(this)).obtenerCotizacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse> OperacionCaja.ServiceReferenceCotizacion.ICotizacion.obtenerCotizacionAsync(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionResponse> obtenerCotizacionAsync(string idSesion, int codigo) {
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest inValue = new OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            return ((OperacionCaja.ServiceReferenceCotizacion.ICotizacion)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse OperacionCaja.ServiceReferenceCotizacion.ICotizacion.obtenerCotizaciones(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest request) {
            return base.Channel.obtenerCotizaciones(request);
        }
        
        public OperacionCaja.ServiceReferenceCotizacion.TWSCotizacion[] obtenerCotizaciones(string idSesion) {
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest inValue = new OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest();
            inValue.idSesion = idSesion;
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse retVal = ((OperacionCaja.ServiceReferenceCotizacion.ICotizacion)(this)).obtenerCotizaciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse> OperacionCaja.ServiceReferenceCotizacion.ICotizacion.obtenerCotizacionesAsync(OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest request) {
            return base.Channel.obtenerCotizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesResponse> obtenerCotizacionesAsync(string idSesion) {
            OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest inValue = new OperacionCaja.ServiceReferenceCotizacion.obtenerCotizacionesRequest();
            inValue.idSesion = idSesion;
            return ((OperacionCaja.ServiceReferenceCotizacion.ICotizacion)(this)).obtenerCotizacionesAsync(inValue);
        }
    }
}
