//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionCaja.ServiceReferenceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.IProducto")]
    public interface IProducto {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uProductoIntf-IProducto) del mensaje obtenerProductoRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uProductoIntf-IProducto#obtenerProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse obtenerProducto(OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uProductoIntf-IProducto#obtenerProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse> obtenerProductoAsync(OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:uProductoIntf-IProducto) del mensaje modificarStockRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:uProductoIntf-IProducto#modificarStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OperacionCaja.ServiceReferenceProducto.modificarStockResponse modificarStock(OperacionCaja.ServiceReferenceProducto.modificarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uProductoIntf-IProducto#modificarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.modificarStockResponse> modificarStockAsync(OperacionCaja.ServiceReferenceProducto.modificarStockRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:uProductoIntf")]
    public partial class TWSProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nombreField;
        
        private double precioField;
        
        private int stockField;
        
        /// <comentarios/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        public double Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <comentarios/>
        public int Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProducto", WrapperNamespace="urn:uProductoIntf-IProducto", IsWrapped=true)]
    public partial class obtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int codigo;
        
        public obtenerProductoRequest() {
        }
        
        public obtenerProductoRequest(string idSesion, int codigo) {
            this.idSesion = idSesion;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoResponse", WrapperNamespace="urn:uProductoIntf-IProducto", IsWrapped=true)]
    public partial class obtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public OperacionCaja.ServiceReferenceProducto.TWSProducto @return;
        
        public obtenerProductoResponse() {
        }
        
        public obtenerProductoResponse(OperacionCaja.ServiceReferenceProducto.TWSProducto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarStock", WrapperNamespace="urn:uProductoIntf-IProducto", IsWrapped=true)]
    public partial class modificarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int incremento;
        
        public modificarStockRequest() {
        }
        
        public modificarStockRequest(string idSesion, int codigo, int incremento) {
            this.idSesion = idSesion;
            this.codigo = codigo;
            this.incremento = incremento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarStockResponse", WrapperNamespace="urn:uProductoIntf-IProducto", IsWrapped=true)]
    public partial class modificarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public modificarStockResponse() {
        }
        
        public modificarStockResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoChannel : OperacionCaja.ServiceReferenceProducto.IProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoClient : System.ServiceModel.ClientBase<OperacionCaja.ServiceReferenceProducto.IProducto>, OperacionCaja.ServiceReferenceProducto.IProducto {
        
        public ProductoClient() {
        }
        
        public ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse OperacionCaja.ServiceReferenceProducto.IProducto.obtenerProducto(OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest request) {
            return base.Channel.obtenerProducto(request);
        }
        
        public OperacionCaja.ServiceReferenceProducto.TWSProducto obtenerProducto(string idSesion, int codigo) {
            OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest inValue = new OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse retVal = ((OperacionCaja.ServiceReferenceProducto.IProducto)(this)).obtenerProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse> OperacionCaja.ServiceReferenceProducto.IProducto.obtenerProductoAsync(OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest request) {
            return base.Channel.obtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.obtenerProductoResponse> obtenerProductoAsync(string idSesion, int codigo) {
            OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest inValue = new OperacionCaja.ServiceReferenceProducto.obtenerProductoRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            return ((OperacionCaja.ServiceReferenceProducto.IProducto)(this)).obtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCaja.ServiceReferenceProducto.modificarStockResponse OperacionCaja.ServiceReferenceProducto.IProducto.modificarStock(OperacionCaja.ServiceReferenceProducto.modificarStockRequest request) {
            return base.Channel.modificarStock(request);
        }
        
        public int modificarStock(string idSesion, int codigo, int incremento) {
            OperacionCaja.ServiceReferenceProducto.modificarStockRequest inValue = new OperacionCaja.ServiceReferenceProducto.modificarStockRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            inValue.incremento = incremento;
            OperacionCaja.ServiceReferenceProducto.modificarStockResponse retVal = ((OperacionCaja.ServiceReferenceProducto.IProducto)(this)).modificarStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.modificarStockResponse> OperacionCaja.ServiceReferenceProducto.IProducto.modificarStockAsync(OperacionCaja.ServiceReferenceProducto.modificarStockRequest request) {
            return base.Channel.modificarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCaja.ServiceReferenceProducto.modificarStockResponse> modificarStockAsync(string idSesion, int codigo, int incremento) {
            OperacionCaja.ServiceReferenceProducto.modificarStockRequest inValue = new OperacionCaja.ServiceReferenceProducto.modificarStockRequest();
            inValue.idSesion = idSesion;
            inValue.codigo = codigo;
            inValue.incremento = incremento;
            return ((OperacionCaja.ServiceReferenceProducto.IProducto)(this)).modificarStockAsync(inValue);
        }
    }
}
